# Generated by Django 5.0.6 on 2024-06-09 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDetailStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registeredUserNumber', models.CharField(max_length=15, unique=True)),
                ('userEmailId', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactStoreBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactName', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('ContactEmailId', models.EmailField(blank=True, max_length=254, null=True)),
                ('ContactSpamValue', models.FloatField(default=0.0)),
                ('ContactIsSpam', models.BooleanField(default=False)),
                ('registeredContactOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contact_validation_api.registeredappuser')),
            ],
        ),
    ]
